from os import name
from typing import Pattern
from django.urls import path
from django.views.generic.base import TemplateView
from .import views

urlpatterns = [
    path("", views.HomePage.as_view(), name="homepage"),
    path("blank",views.Blank.as_view(), name="blank"),
    path("login", views.user_login, name="user_login"),
    path("register", views.register, name="register"),
    path("user_logout", views.user_logout, name="user_logout"),
    path("product/<slug>", views.ProductView.as_view(), name="product"),
    path("checkout", views.CheckOutView.as_view(), name="checkout"),
    path("categories", views.CategoryView.as_view(), name="category"),
    path("categories/<name>", views.ProductsinCategoryView.as_view(), name="productsincategory"),
    path("card", views.CardView.as_view(), name="card"),
    path("profile", views.ProfileView.as_view(), name="profile"),
    path("comments/<slug:slug>/<int:page>", views.CommentView.as_view(), name="comments"),
    path("changepassword", views.ChangePasswordView.as_view(), name="changepassword"),
    path("profile/address", views.ViewAddress.as_view(), name="address"),
    path("profile/address/add", views.AddAddress.as_view(), name="add_address"),
    path("profile/address/edit/<int:id>", views.EditAddress.as_view(), name="edit_address"),
    path("profile/address/delete/<int:id>", views.DeleteAddress.as_view(), name="delete_address"),
    path("forgotpassword", views.ForgotPasswordView.as_view(), name="forgotpassword"),
    path("check_code", views.CheckCodeView.as_view(), name="check_code"),
    path("enternewpassword", views.EnterNewPasswordView.as_view(), name="enternewpassword"),
    path("updatephoto", views.UpdatePhotoView.as_view(), name="updatephoto"),
    path("orders", views.OrderView.as_view(), name="myorders"),
    path("wishlist", views.WishListView.as_view(), name="wishlist"),
    path("search", views.SearchView.as_view(), name="search"),
    path("about", TemplateView.as_view(template_name="about.html"), name="about"),
    path("faq", views.FAQView.as_view(), name="faq"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path("order_confirmation", views.OrderConfirmationView.as_view(), name="order_confirmation"),
    path("payment_methods", views.PaymentMethods.as_view(), name="payment_methods"),
    path("payment_methods/add_cart", views.AddCart.as_view(), name="add_cart"),
    path("addproduct", views.AddProductbyAdmin.as_view(), name="addproduct"),
    path("privacypolicy", TemplateView.as_view(template_name="privacy_policy.html"), name="privacypolicy"),
    path("cancelorder", views.CancelOrder.as_view(), name="cancelorder"),
    path("signupforupdates", views.signupforupdates, name="signupforupdates"),
    path("orders/<id>", views.SingleOrder.as_view(), name="singleorder"),
    path("docomment", views.DoComment.as_view(), name="docomment"),
    path("return/<id>", views.ReturnProduct.as_view(), name="returnproduct"),
    path("admin2/products", views.AdminProducts.as_view(), name="adminproducts"),
    path("admin2/products/<name>", views.AdminProductsEach.as_view(), name="adminproductseach"),
    path("admin2/products/<name>/add", views.AdminAddProductsEach.as_view(), name="adminaddproductseach"),
    path("admin2/products/delete/<id>", views.AdminDeleteProductsEach, name="admindeleteproductseach"),
    path("admin2/brands", views.AdminBrands, name="adminbrands"),
    path("admin2/brands/add", views.AdminAddBrand, name="adminaddbrand"),
    path("admin2/categories", views.AdminCategories, name="admincategories"),
    path("admin2/categories/add", views.AdminAddCategory, name="adminaddcategory"),
    path("admin2/customers", views.AdminCustomers, name="admincustomers"),
    path("admin2/customers/delete/<id>", views.AdminDeleteCustomer, name="admindeletecustomer")
]