# Generated by Django 3.2.8 on 2021-11-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='brands')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics.marka'),
        ),
    ]
