# Generated by Django 3.2.8 on 2021-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_auto_20211103_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marka',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
