# Generated by Django 3.2.8 on 2021-11-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_alter_marka_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
