# Generated by Django 3.2.8 on 2021-11-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0007_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_applied',
            field=models.BooleanField(null=True),
        ),
    ]
