# Generated by Django 3.2.8 on 2021-11-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0008_discount_is_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='is_applied',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_applied',
            field=models.BooleanField(null=True),
        ),
    ]
