# Generated by Django 3.2.8 on 2021-11-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0009_auto_20211103_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics.category'),
        ),
    ]
