# Generated by Django 3.2.8 on 2021-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0010_spec_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='category',
        ),
        migrations.AddField(
            model_name='spec',
            name='category',
            field=models.ManyToManyField(null=True, to='electronics.Category'),
        ),
    ]
