# Generated by Django 3.2.8 on 2021-11-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0011_auto_20211104_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='kind',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
