# Generated by Django 3.2.8 on 2021-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0015_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='b_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
