# Generated by Django 3.2.8 on 2021-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0016_auto_20211105_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.ManyToManyField(blank=True, to='electronics.Address'),
        ),
    ]
