# Generated by Django 3.2.8 on 2021-11-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0017_alter_userinfo_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='electronics.Color'),
        ),
    ]
