# Generated by Django 3.2.8 on 2021-11-22 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electronics', '0019_auto_20211123_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.payment'),
        ),
    ]
