# Generated by Django 3.2.8 on 2021-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0020_auto_20211123_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='created_at',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ManyToManyField(null=True, to='electronics.Product'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
