# Generated by Django 3.2.8 on 2021-11-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0025_alter_orderdetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ManyToManyField(null=True, to='electronics.Product'),
        ),
    ]
