# Generated by Django 3.2.8 on 2021-11-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0032_alter_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marka',
            name='Category',
            field=models.ManyToManyField(to='electronics.Category'),
        ),
    ]
