# Generated by Django 3.2.8 on 2021-11-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0033_marka_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marka',
            old_name='Category',
            new_name='category',
        ),
    ]
