# Generated by Django 3.2.8 on 2021-11-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0035_remove_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted_at',
        ),
    ]
