# Generated by Django 3.2.8 on 2021-11-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0036_remove_product_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
