# Generated by Django 3.2.8 on 2021-11-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0037_alter_userinfo_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
