# Generated by Django 3.2.8 on 2021-11-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0042_remove_virtualcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcard',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
