# Generated by Django 3.2.8 on 2021-11-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0043_alter_virtualcard_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
