# Generated by Django 3.2.8 on 2021-11-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0045_auto_20211128_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
