# Generated by Django 3.2.8 on 2021-11-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0047_virtualcard_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
