# Generated by Django 3.2.8 on 2021-12-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0052_updateemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.ManyToManyField(blank=True, null=True, to='electronics.Specs'),
        ),
    ]
