# Generated by Django 3.2.8 on 2021-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0054_orderdetail_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_returned',
            field=models.BooleanField(null=True),
        ),
    ]
